### PR TITLE
Feature token authentication

### PR DESCRIPTION
**Pull request by doubleO8**
Authentication Token Support …

New parameter _token_ may be used to provide a VersionOne authentication
token when instantiating a V1Meta/V1Server object.

### CODE REVIEW

**Comment by neronmoon** [comment]
:+1:

**Comment by fahrenberger** [comment]
Any idea why this is not being pursued further? Seems like an incredibly useful feature!

The version here still crashes and burns if something goes wrong during the authentication process (we might need to catch some exceptions), but it essentially seems to work. Definitely +1.

**Comment by narfman0** [comment]
Tokens would be handy!

If I were maintaining this, I'd ask the PR (e81eef4) be split. So much whitespace changes add clutter and obscure the functional changes. Easy to produce conflicts, too. @doubleO8

**Comment by doubleO8** [comment]
While evaluating the API I realised that the lack of token support is the least of its problems and the maintainer's repository update rate speaks for itself too.
Thus I gave up on it and created the [versio9](https://pypi.python.org/pypi/versio9/) [fork](https://github.com/doubleO8/versionone-sdk-spoon) which works well enough for my needs.

@narfman0 the whitespace changes would have been an improvement, wouldn't they? ;)

**Comment by walkerrandolphsmith** [comment]
I did the same @doubleO8 https://github.com/walkerrandolphsmith/VersionOne.SDK.Python/. Your implementation is something I will take note of. The api of my repo is similar to the api of the VersionOne.SDK.Javascript repo.

**Pull request closed without merging**
